name = "znet-rpc"
main = "worker.js"
compatibility_date = "2024-02-16"

[vars]
NODE_RPC_URL = "http://217.70.184.38:8449"

[build]
command = "npm run build"
[build.environment]
NODE_VERSION = "20.0.0" 